services:
  - type: web
    name: your-django-app
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn your_project_name.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: your-django-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: SECRET_KEY
        generateValue: true